# Generated by Django 2.2.5 on 2019-09-19 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapis', '0002_outdoordate_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outdoordate',
            name='picture_url',
        ),
        migrations.AddField(
            model_name='outdoordate',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
