# Generated by Django 2.2.5 on 2019-09-19 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapis', '0004_auto_20190919_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outdoordate',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
