# Generated by Django 2.2.5 on 2019-09-09 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190909_1741'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OutdoorDate',
        ),
    ]
